# Generated by Django 5.0.7 on 2024-07-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scpwikiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='content',
        ),
    ]
